package com.cloudframe.app.common;
/* Java Code Generated by CloudFrame */ 
import com.cloudframe.app.utility.CFUtil;
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] SPACE_48 = CFUtil.fillSpaces(48);
public static final char[] FORMAT_287469588 = "---------9".toCharArray();
public static final char[] LITERAL_1007886308 = "TRADING.QUEUE                                   ".toCharArray();
 
}
